### ISSUE TITLE
Action fails when release doesn't exist even with doNotFailIfNotFound: true

### ISSUE THREAD

**Issue by AvivPeledTalon** [cardinalby/git-get-release-action#15]
My team's been using this action for quite a while now to make sure a release does NOT exist.
We just pass doNotFailIfNotFound: true, and ignore the "release not found" warning.
Yesterday this stopped working and the step started failing our workflows with 
`Error: HttpError: Not Found`

I don't see any changes on your side so I'm guessing something changed on Github's side of things.

**Comment by cardinalby** [comment]
Hi! Do you have a full error text? You also may try to generate a personal access token with a required scope and pass it to GITHUB_TOKEN env variable for the action since GitHub can prohibit some requests with default one.

Let me know if it helps, I would add it to the docs

**Comment by AvivPeledTalon** [comment]
> Hi! Do you have a full error text? You also may try to generate a personal access token with a required scope and pass it to GITHUB_TOKEN env variable for the action since GitHub can prohibit some requests with default one.
> 
> Let me know if it helps, I would add it to the docs

Hi! Thanks for the quick response. 
I've investigated it further and I think Github changed the way they answer to requests for releases, and now return 404 if the release doesn't exist, I believe it used to be 200 ok with response body "Not found", so if that's what your'e looking for that would explain what I'm seeing.

**Comment by cardinalby** [comment]
Thx, you gave me a hint, but I'm not sure I completely understand the cause. Fortunately, I have some integration tests and I found they are failing now for the case you mention. I don't use direct API requests, but octokit library for that. I found now it returns an error with `"404"` code (string) instead of `404` (number) in case of not found release. Not sure I understand why it happens and how the actual status code is mapped inside the library, it's weird JS thing for me, who is now is stuck to strictly typed languages :)) But it seems that replacing `===` comparison with `==` works now. 

I pushed it to `master` as well as to `v1`, pls check if it works for you now. Still happy to hear any explanation :)

**Comment by malchiste** [comment]
I had this issue as well, and error is now gone for me! thank you

**Comment by just-ero** [comment]
Still having the same issue on my end. Not doing anything fancy:
```yml
- name: Fetch previous release
  id: previous-release
  uses: cardinalby/git-get-release-action@v1
  env:
    GITHUB_TOKEN: ${{ github.token }}
  with:
    latest: true
    prerelease: ${{ !inputs.pre_release && 'false' || '' }}
    doNotFailIfNotFound: true
```

**Comment by cardinalby** [comment]
Hi, @just-ero ! Thanks for highlighting, it's a separate logic branch for the "latest" release, pls try again, just updated `master` and `v1`

**Comment by just-ero** [comment]
Fixed, thanks.

**Comment by AvivPeledTalon** [comment]
Thanks! Great work!
